# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.Product')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='rent',
            name='products',
        ),
        migrations.AddField(
            model_name='rent',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
